version: "3.9"

services:
  sync-middleware:
    container_name: tc_middleware
    restart: unless-stopped
    image: localhost/tcweb-middleware:dev
    build:
      context: middleware
    env_file:
      - .env 
    volumes:
      - middlewaredata:/app/data:z
    depends_on:
      - tc-syncserver
    ports:
      - "3001:3001"
    networks:
      - tc_network

  tcweb-backend:
    container_name: tc_backend
    restart: unless-stopped
    image: localhost/tcweb-backend:dev
    build:
      context: backend
    env_file:
      - .env 
    volumes:
      - backenddata:/app/data:z
      - backendconfig:/app/config:z
    ports:
      - "8080:8080"
    depends_on:
      - sync-middleware
    networks:
      - tc_network

  tc-syncserver:
    container_name: tc_syncserver
    restart: unless-stopped
    image: ghcr.io/gothenburgbitfactory/taskchampion-sync-server:0.7.1
    env_file:
      - .env
    volumes:
      - syncdata:/app/data:z
    ports:
      - "8081:8080"
    networks:
      - tc_network

  tcweb-frontend:
    container_name: tc_frontend
    restart: unless-stopped
    image: localhost/tcweb-frontend:dev
    build:
      context: frontend 
    env_file:
      - .env 
    ports:
      - "4200:80"
    networks:
      - tc_network

volumes:
  syncdata:
  middlewaredata:
  backenddata:
  backendconfig:

networks:
  tc_network:
    driver: bridge
