
stages:
  - test
  - build

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cargo/
    - target/

stages:
  - test
  - build
 

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  RUST_VERSION: "1.93"

include:
  - local: .gitlab/ci/middleware.yml
