cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .cargo/
    - target/

stages:
  - lint
  - test
  - build
  - release

variables:
  CARGO_HOME: $CI_PROJECT_DIR/.cargo
  RUST_VERSION: '1.93.1'
  GOLANGCI_LINT_VERSION: '2.8.0'

include:
  - local: .gitlab/ci/middleware.yml
  - local: .gitlab/ci/backend.yml
  - local: .gitlab/ci/deploy_container_github.yml
